### ISSUE TITLE
Implement custom 404.html to rewrite URL from pointing to master branch to the latest version

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/rustdocs#12]
resource:
- https://docs.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site
- https://lea.verou.me/2016/11/url-rewriting-with-github-pages/

**Comment by danforbes** [comment]
I do not think we want to perform this redirect, unfortunately...this is confusing for our users. If they type `master` in the URL bar, that _means_ something and we do not want to redirect them to something different. From my POV, the decision to remove `master` from our Rustdocs was made for a reason, and we need to stand by that reason, not hide it. We want to encourage people to use tagged versions of Substrate...people should not "think" in terms of using `master`. I think it would be fine to create a convenience redirect from some pseudo-tag like `latest`, but I do not think we should redirect `master` in particular. The system that we set up is that if someone wants `master` they use crates.parity.io and if they want a supported, released version they use substrate.dev/rustdocs.

**Comment by jimmychu0807** [comment]
aah. Does that mean we can have
https://substrate.dev/rustdocs/master/sp_runtime/offchain/storage_lock/index.html
redirects to 
https://crates.parity.io/sp_runtime/offchain/storage_lock/index.html

I see you reason, and I want to cover the ground that existing links of `https://substrate.dev/rustdocs/master/` do not break.

**Comment by danforbes** [comment]
That's a great idea, Jimmy!

**Comment by jimmychu0807** [comment]
@danforbes If you are happy with the redirect & commit https://github.com/substrate-developer-hub/rustdocs/commit/6b7fe00beb110cc605f5fb8d78811add5bf8ac79, we can close this.

To test:
- https://substrate.dev/rustdocs/abcdefg -> still show the default error page 
- https://substrate.dev/rustdocs -> still redirect to the latest tagged version of substrate rustdoc
- https://substrate.dev/rustdocs/master -> redirect to `https://crates.parity.io`
- https://substrate.dev/rustdocs/master/* -> redirect to `https://crates.parity.io/*`, try with https://substrate.dev/rustdocs/master/sp_runtime/offchain/storage_lock/index.html

**Comment by danforbes** [comment]
Great work, @jimmychu0807 :pray:
